Make the classic output span the actual width of the tty so you can see the actual path with a long file name.
nicfit/eyeD3 pull request #92
Opened 2017-09-25 02:12 UTC by redshodan

Example, before and after:

```
baron@dib ~/src/eyeD3 $ eyeD3 "/data/tater-salad-music/The Cure/1979.05.09 - Peel Session/Cure, The - 01 - Desperate Journalist In Ongoing Meaningful Review Situation.mp3"
...Desperate Journalist In Ongoing Meaningful Review Situation.mp3 [ 3.07 MB ]
-------------------------------------------------------------------------------
Time: 02:40	MPEG1, Layer III	[ 160 kb/s @ 44100 Hz - Joint stereo ]
-------------------------------------------------------------------------------
ID3 v2.4:
title: Desperate Journalist In Ongoing Meaningful Review Situation
artist: Cure, The
album: Peel Session
album artist: None
recording date: 1979
track: 1/5		genre: Alternative (id 20)
Comment: [Description: ] [Lang: XXX]
May 9, 1979
-------------------------------------------------------------------------------
baron@dib ~/src/eyeD3 $ PYTHONPATH=src python -m eyed3.main "/data/tater-salad-music/The Cure/1979.05.09 - Peel Session/Cure, The - 01 - Desperate Journalist In Ongoing Meaningful Review Situation.mp3"
/data/tater-salad-music/The Cure/1979.05.09 - Peel Session/Cure, The - 01 - Desperate Journalist In Ongoing Meaningful Review Situation.mp3                                                             [ 3.07 MB ]
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Time: 02:40	MPEG1, Layer III	[ 160 kb/s @ 44100 Hz - Joint stereo ]
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
ID3 v2.4:
title: Desperate Journalist In Ongoing Meaningful Review Situation
artist: Cure, The
album: Peel Session
album artist: None
recording date: 1979
track: 1/5		genre: Alternative (id 20)
Comment: [Description: ] [Lang: XXX]
May 9, 1979
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

2017-09-25 20:00 UTC, nicfit requested changes

2017-09-25 20:00 UTC, nicfit commented on src/eyed3/utils/console.py
> +        except:
Can you list the expceptions to pass on?

2017-09-25 21:20 UTC, redshodan commented
Done.

2017-09-26 00:53 UTC, nicfit approved these changes

2017-09-26 00:53 UTC, merged